#!/bin/sh

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

ROOT=$DIR/..
WEB=$ROOT/web
BUILD=$WEB/build
DEPLOY=$ROOT/../boondocker-deploy
DEPLOY_BUILD=$DEPLOY/build

echo Cleaning build folder                              && \
rm -rf web/index.html web/build/bundle.js               && \
echo Switching to no test mode                          && \
echo "module.exports = false" > $WEB/js/testing.js      && \
echo Generating bundle, index.html and data if needed   && \
make -C $ROOT bundle-min                                && \
make -C $ROOT index                                     && \
[ -f $BUILD/data.js ] || make -C $ROOT data             && \
echo Cleaning old deploy                                && \
rm -rf $DEPLOY/*                                        && \
echo Copying files to deploy                            && \
mkdir -p $DEPLOY_BUILD                                  && \
cp -R $WEB/css $DEPLOY/css                              && \
cp -R $WEB/img $DEPLOY/img                              && \
cp -R $WEB/deps $DEPLOY/deps                            && \
cp $WEB/{index.html,favicon.ico} $DEPLOY                && \
cp $BUILD/* $DEPLOY_BUILD/                              && \
git co $WEB/js/testing.js                               && \
echo Deploying ...                                      && \
(cd $DEPLOY                                             && \
  git reset -- README.md                                && \
  git checkout -- README.md                             && \
  git add .                                             && \
  git commit -m "deploy at `date +'%Y/%m/%d %H:%M:%S'`" && \
  git push origin gh-pages)
