#!/bin/sh

CURRENT_BRANCH=`git rev-parse --abbrev-ref HEAD`

rm -rf web/index.html web/build/bundle.js           && \
git checkout gh-pages                               && \
git reset --hard master                             && \
make data                                           && \
make bundle-min                                     && \
make index                                          && \
git add -f web/index.html web/build/bundle.js       && \
git add -f web/build/data.js                        && \
git commit -m "ghp: adding bundles and index.html"  && \
git push -f origin gh-pages                         && \
make clean                                          && \
git checkout $CURRENT_BRANCH
